# Generated by Django 3.0.4 on 2020-04-25 14:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_billingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderadd',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('zip', models.CharField(max_length=100)),
            ],
        ),
    ]
