# Generated by Django 3.0.4 on 2020-04-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200428_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderadd',
            name='amount',
        ),
    ]
